<a href="https://colab.research.google.com/github/V1LL4pro/Deep-Learning/blob/Corte-1/T1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install openpyxl

from google.colab import files
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler

# Subir el archivo Excel
subiditos = files.upload()

# Obtener nombre del archivo
archivito = next(iter(subiditos))

# Mostrar hojas disponibles
excelito = pd.ExcelFile(archivito)
print("\nHojas disponibles:", excelito.sheet_names)

# Seleccionar hoja
hojita_seleccionada = input("\nIngresa el nombre de la hoja a usar: ")

# Leer datos
dataframecito = pd.read_excel(archivito, sheet_name=hojita_seleccionada)

# 1. Eliminar valores nulos
dataframecito_limpio = dataframecito.dropna()

# 2. Convertir columna de género
columnita_genero = dataframecito_limpio.columns[1]
dataframecito_limpio[columnita_genero] = dataframecito_limpio[columnita_genero].replace({
    'FEMENINO': 0,
    'MASCULINO': 1
})

# 3. Normalización entre 0-1
columnitas_normalizar = dataframecito_limpio.columns.difference([columnita_genero])
escaloncito = MinMaxScaler()
dataframecito_limpio[columnitas_normalizar] = escaloncito.fit_transform(dataframecito_limpio[columnitas_normalizar])

# 4. Convertir a numpy array y tensor
arreglito_numpy = dataframecito_limpio.values.astype(np.float32)
tensorcito = tf.convert_to_tensor(arreglito_numpy, dtype=tf.float32)

# Mostrar resultados
print("\nDatos como Numpy Array:")
print(arreglito_numpy)
print("\nForma del array:", arreglito_numpy.shape)
print("\nDatos como Tensor:")
print(tensorcito)

Saving Diagnostico.xlsx to Diagnostico (9).xlsx

Hojas disponibles en el archivo: ['Datos', 'Hoja2']

Ingresa el nombre de la hoja que deseas usar: Datos

Datos como Numpy Array:
[[0.         1.         0.775      ... 0.06175299 0.         0.34890965]
 [0.         1.         0.575      ... 0.57270914 0.42313117 0.5451713 ]
 [0.         1.         0.85       ... 0.1434263  0.14104372 0.35825545]
 ...
 [0.93333334 1.         0.4        ... 0.48406374 0.83215797 0.63862926]
 [1.         0.         0.475      ... 0.3446215  0.42313117 0.78504676]
 [1.         0.         0.1        ... 0.4322709  0.5641749  0.44548288]]

Forma del array: (442, 12)

Datos como Tensor:
tf.Tensor(
[[0.         1.         0.775      ... 0.06175299 0.         0.34890965]
 [0.         1.         0.575      ... 0.57270914 0.42313117 0.5451713 ]
 [0.         1.         0.85       ... 0.1434263  0.14104372 0.35825545]
 ...
 [0.93333334 1.         0.4        ... 0.48406374 0.83215797 0.63862926]
 [1.         0.      

<ipython-input-11-ca4410c42c10>:30: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataframecito_limpio[columnita_genero] = dataframecito_limpio[columnita_genero].replace({
